#################
### AUTOSTART ###
#################

exec-once = tmux &
exec-once = awww-daemon &
exec-once = awww img -t none git/dots/wallpapers/blankLight.png &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store 
exec-once = hyprctl setcursor gruvcursor 26 &
exec-once = kitty

