--################
--## AUTOSTART ###
--################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("tmux &")
    hl.exec_cmd("awww-daemon &")
    hl.exec_cmd("awww img -t none git/dots/wallpapers/blankLight.png &")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor gruvcursor 26 &")
    hl.exec_cmd("kitty")
end)

