#################
### AUTOSTART ###
#################

exec-once = waybar &
exec-once = swww-daemon &
exec-once = swww img ~/git/dots/wallpapers/burning-earth.png &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store 
exec-once = hyprctl setcursor gruvcursor 26 &

