--##################
--## KEYBINDINGS ###
--##################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

local terminal = "kitty"
local code = "kitty -e nvim"
local browser = "~/.config/hypr/scripts/librewolf.sh"
local menu = "rofi"
local fileManager = "ranger"

-- Applications
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd(terminal .. " -e " .. fileManager))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(menu .. " -show drun"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd(menu .. " -show run"))
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd(menu .. " -show window"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(terminal .. " -e nvim"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("sioyek"))

--barless let's go!
hl.bind(mainMod .. " + code:60", hl.dsp.exec_cmd("killall waybar"))
hl.bind(mainMod .. " + code:59", hl.dsp.exec_cmd("waybar"))

-- Scripts
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/screenshot.sh"))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -al"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist wipe"))

-- Kill 
hl.bind(mainMod .. " + A", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("shutdown now"))
hl.bind(mainMod .. " + ALT + Q", hl.dsp.exec_cmd("systemctl suspend"))
hl.bind(mainMod .. " + CONTROL + Q", hl.dsp.exit())

-- floating
hl.bind(mainMod .. " + W", hl.dsp.window.float({ action = "toggle" }))
--bind = $mainMod, M, togglesplit,
hl.bind(mainMod .. " + Return", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

-- Move focus 
hl.bind(mainMod .. " + N", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + O", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + I", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + E", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces 
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace 
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
